name: Build and push teamcity-build-agent containers

on:
  workflow_dispatch:
  push:
    paths:
    - 'teamcity-build-agent/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        agent_version: ['net5.0-base']
    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: teamcity-build-agent/${{ matrix.agent_version }}
        file: teamcity-build-agent/${{ matrix.agent_version }}/Dockerfile
        push: true
        platforms: linux/amd64
        tags: 1node/teamcity-build-agent:${{ matrix.agent_version }}
