name: Build and push teamcity-build-agent containers

on:
  workflow_dispatch:
  push:
    paths:
    - 'teamcity-build-agent/**'

jobs:
  build-base:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push base
      id: docker_build_base
      uses: docker/build-push-action@v3
      with:
        context: teamcity-build-agent/base
        file: teamcity-build-agent/base/Dockerfile
        push: true
        platforms: linux/amd64
        tags: 1node/teamcity-build-agent:base

  build:
    runs-on: ubuntu-latest
    needs: build-base
    strategy:
      matrix:
        agent_version: ['net5', 'net6', 'net7', 'dotnet-full', 'android-base']
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push matrix
      id: docker_build_agents
      uses: docker/build-push-action@v3
      with:
        context: teamcity-build-agent/${{ matrix.agent_version }}
        file: teamcity-build-agent/${{ matrix.agent_version }}/Dockerfile
        push: true
        platforms: linux/amd64
        tags: 1node/teamcity-build-agent:${{ matrix.agent_version }}
