name: Build and push php-nginx containers

on:
  workflow_dispatch:
  push:
    paths:
    - 'nginx-php/**'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ['8.0', '8.1', '8.2']
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      id: buildx
      with:
        install: true
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        build-args: PHP_VERSION=${{ matrix.php_version }}
        context: nginx-php
        file: nginx-php/Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        tags: kosar/nginx-php:${{ matrix.php_version }}
