name: Build and push azure webapp-deploy

on:
  workflow_dispatch:
  push:
    paths:
    - 'azure/webapp-deploy/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Get version number
      id: version
      run: |
        ver=$(curl -s https://api.github.com/repos/Azure/webapps-deploy/releases/latest | grep "tag_name" | cut -d '"' -f 4 | cut -c2-)
        echo ::set-output name=version::$ver
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: squid-proxy
        file: azure/webapp-deploy/Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        tags: kosar/azure-webapp-deploy:latest, kosar/azure-webapp-deploy:${{ steps.version.outputs.version }}
